version: "3.3"

services:
    mariadb:
        image: mariadb:10.5.9-focal
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=mypassword
        volumes:
            - ./mysql:/etc/mysql
            - ./mysql_data:/var/data
        networks:
            kvts:
                ipv4_address: 172.12.0.2

    wordpress:
        build: ./wordpress
        ports:
            - 8082:8000
        volumes:
            - ./wordpress/app:/home
            - ./wp-content:/home/wp-content
        networks:
            - kvts

networks:
    kvts:
        ipam:
            driver: default
            config:
                - subnet: 172.12.0.0/24
