version: "3.3"

services:
    wordpress:
        build: ./wordpress
        ports:
            - 8082:8000
        volumes:
            - ./wordpress/app:/home
            - ./wordpress/wp-content:/home/wp-content
        networks:
            - kvts
networks:
    kvts:
        ipam:
            driver: default
            config:
                - subnet: 172.12.0.0/24
