version: "2.2"
services:
  wordpress:
    image: registry.gitlab.com/a8551/caradietmudah/caradietmudah.com:prod
    # image: nginx:alpine
    volumes:
        - ./wordpress/wp-content:/home/wp-content
    labels:
      - traefik.enable=true
      - traefik.http.routers.myflimtysvc.entrypoints=https
      - traefik.http.routers.myflimtysvc.tls.certresolver=myresolver
      - traefik.http.routers.myflimtysvc.rule=Host(`malaysia.flimty.co`)
      - traefik.http.routers.myflimty.entrypoints=web
      - traefik.http.routers.myflimty.rule=Host(`malaysia.flimty.co`)
      - traefik.http.routers.myflimty.service=svc_flimtymy
      - traefik.http.services.svc_flimtymy.loadbalancer.server.port=80
      - traefik.http.routers.myflimtysvc.service=svc_flimtymy2
      - traefik.http.services.svc_flimtymy2.loadbalancer.server.port=80 
networks:
    default:
        name: ikamai_apps
        external: true
