version: "2.2"
services:
  wordpress:
    image: registry.gitlab.com/aimi-new/wordpress/caradietmudah.com
    # image: nginx:alpine
    volumes:
      - ./wordpress/wp-content:/home/wp-content
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.my-compress.compress=true
      - traefik.http.routers.caradietmudah.rule=Host(`caradietmudah.com`)
      - traefik.http.routers.caradietmudah.entrypoints=https,web
      - traefik.http.routers.caradietmudah.tls.certresolver=myresolver
      - traefik.http.routers.caradietmudah.service=svc_caradietmudah
      - traefik.http.services.svc_caradietmudah.loadbalancer.server.port=80
      - traefik.http.routers.caradietmudah.middlewares=my-compress
networks:
  default:
    name: ikamai_apps
    external: true
