version: "3.3"

services:
    wordpress:
        build: .
        ports:
            - 8082:80
        volumes:
            # - ./wordpress/app:/home
            - ./wordpress/wp-content:/home/wp-content
        labels:
            - traefik.enable=true
            - traefik.http.routers.flimty_my_web.rule=Host(`flimty.localhost`)
            - traefik.http.routers.flimty_my_web.entrypoints=web
            - traefik.http.routers.flimty_my_web.service=flimty_my_web_service
            - traefik.http.services.flimty_my_web_service.loadbalancer.server.port=80
        networks:
            superapp_network:
networks:
    superapp_network: